[package]
name = "by-cli"
version = "0.0.0"
edition.workspace = true
license.workspace = true
build = "build.rs"

[[bin]]
name = "by-rs"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
by-config.workspace = true
by-llm.workspace = true
by-memory.workspace = true
by-persist.workspace = true
by-registry.workspace = true
by-tui.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
rusqlite.workspace = true
tempfile.workspace = true
